- alias: 'Windowlights on when sun sets'
  trigger:
    platform: sun
    event: sunset
  action:
    service: switch.turn_on
    entity_id: group.custom_all_lights
- alias: 'Windowlights off when sun rises'
  trigger:
    platform: sun
    event: sunrise
  action:
    service: switch.turn_off
    entity_id: group.custom_all_lights
    
 #- alias: 'test remote'
 #  trigger:
 #    platform: state
 #    entity_id: light.grupp_1
 #    to: 'off'
 #  action:
 #    service: light.turn_off
 #    entity_id: switch.telldus_tzwp100_plugin_switch_switch
