homeassistant:
  name: Home
  latitude: 59.433776
  longitude: 18.323753
  elevation: 23
  unit_system: metric
  time_zone: Europe/Stockholm
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
#  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: ha.rubble.se
  trusted_networks:
    - 192.168.1.2
    - 192.168.0.110
  ip_ban_enabled: True
  login_attempts_threshold: 5

updater:

discovery:
conversation:
history:
logbook:
map:
sun:
logger:
  default: info
  logs:
    homeassistant.components.deconz: debug
##    homeassistant.components.volvooncall: debug
##    homeassistant.components.*.volvooncall: debug
    deconz: debug
##tellstick:

recorder:
  db_url: !secret mariadb_connection_url

zwave:
  usb_path: /dev/ttyACM0

rfxtrx:
  device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A11SEJ09-if00-port0

deconz:
  host: 192.168.0.222
  api_key: !secret deconz_api_key

influxdb:
  host: 192.168.1.9

nibe:
  client_id: !secret nibe_client_id
  client_secret: !secret nibe_client_secret
  redirect_uri: https://ha.rubble.se/api/nibe/auth
  writeaccess: false # set to true to support climate write (needs new tokens)
  systems:
        - system: 55397
          units:
            - unit: 0
              categories:

sensor:
  - platform: yr
  - platform: rfxtrx
    automatic_add: False
    devices:
      08500700e700011289:
        name: Frys
      0a5209028700010c2b0189:
        name: Baksida
  - platform: mqtt
    state_topic: "home/sparsnas"
    name: "Sparsnäs energy consumption momentary"
    unit_of_measurement: "W"
    value_template: '{{ value_json.Watt | round(1) }}'
  - platform: mqtt
    state_topic: "home/sparsnas"
    name: "Sparsnäs energy consumption over time"
    unit_of_measurement: "kWh"
    value_template: '{{ value_json.kWh | round(1) }}'
  - platform: mqtt
    state_topic: "home/sparsnas"
    name: "Sparsnäs Battery remaining"
    unit_of_measurement: "%"
    value_template: '{{ value_json.battery | round(1) }}'

##  - platform: rest
##    resource: http://192.168.1.9:18003/location?group=home&user=Urban
##    value_template: '{{value_json.users.Urban[0].location}}'
##    method: GET
##    name: Urban Internal location
##    scan_interval: 5
#

# Text to speech
tts:
  - platform: google

mqtt:
  broker: 192.168.1.9
  username: !secret mqtt_username
  password: !secret mqtt_password

mqtt_statestream:
  base_topic: homeassistant
  publish_attributes: true
  publish_timestamps: true

volvooncall:
  username: !secret volvooncall_username
  password: !secret volcooncall_password

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

switch: !include switch.yaml

verisure:
  username: !secret verisure_username
  password: !secret verisure_password

###############################
## INCLUDES

group: !include groups.yaml
automation: !include_dir_merge_list automation
#script: !include scripts.yaml
device_tracker: !include device_tracker.yaml
#
#variable: !include variables.yaml
##binary_sensor: !include binary_sensors.yaml
#panel_custom: !include panel_custom.yaml

