- alias: 'Windowlights on when sun sets'
  trigger:
    platform: sun
    event: sunset
  action:
    service: switch.turn_on
    entity_id: group.custom_all_lights

- alias: 'Windowlights off when sun rises'
  trigger:
    platform: sun
    event: sunrise
  action:
    service: switch.turn_off
    entity_id: group.custom_all_lights

- alias: 'Outsidelights off when sun rises'
  trigger:
    platform: sun
    event: sunrise
  action:
    service: switch.turn_off
    entity_id: group.custom_outside