- alias: 'Set morning when sleep ends'
  trigger: 
    platform: state
    entity_id: switch.sleeping
    to: 'off'
  action:
    service: light.turn_on
    entity_id: light.tradfri_bulb_e27_ws_opal_980lm
    data:
      brightness: 150
   